# Generated by Django 2.2.7 on 2019-11-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('available_seats', models.PositiveSmallIntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('stop', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip_passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('auth_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Users')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Trip_passenger')),
            ],
        ),
        migrations.AddField(
            model_name='trip_passenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Users'),
        ),
        migrations.AddField(
            model_name='trip_passenger',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Users'),
        ),
    ]
