# Generated by Django 2.2.7 on 2019-11-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AlterModelOptions(
            name='trip_passenger',
            options={'ordering': ['-trip']},
        ),
        migrations.AlterModelOptions(
            name='trip_requests',
            options={'ordering': ['-request']},
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trips',
        ),
        migrations.AlterModelTable(
            name='trip_passenger',
            table='trip_passenger',
        ),
        migrations.AlterModelTable(
            name='trip_requests',
            table='trip-requests',
        ),
    ]
